#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "zitadel"
name = "Zitadel"
description.en = "Identity infrastructure"
description.fr = " Infrastructure d'identité"

version = "2.70.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://zitadel.com"
demo = "https://demo.example.com"
admindoc = "https://zitadel.com/docs/self-hosting/deploy/overview"
userdoc = "https://yunohost.org/apps"
code = "https://github.com/zitadel/zitadel"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    # Note that user-provided passwords questions are not automatically saved as setting
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/zitadel/zitadel/releases/download/v2.70.0/zitadel-linux-amd64.tar.gz"
    amd64.sha256 = "9b63ae4be4b967165b8a0d7964f8d67b1573c5a8962cb0b5a2e1f9367d9c1073"
    arm64.url = "https://github.com/zitadel/zitadel/releases/download/v2.70.0/zitadel-linux-arm64.tar.gz"
    arm64.sha256 = "c72f670fc3db912e065a99d1af58de46dda703fd2cdbbba971c5f0fa552ad684"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql, postgresql-contrib"

    [resources.database]
    type = "postgresql"
